In [2]:
import pandas as pd
import numpy as np

# Veri seti boyutu
n_samples = 500

# Rastgele veri oluşturma
np.random.seed(42)
data = {
    'id': range(1, n_samples + 1),
    'soru1': np.random.randint(1, 6, n_samples),
    'soru2': np.random.randint(1, 6, n_samples),
    'soru3': np.random.randint(1, 6, n_samples),
    'soru4': np.random.randint(1, 6, n_samples),
    'soru5': np.random.randint(1, 6, n_samples),
    'soru6': np.random.randint(1, 6, n_samples),
    'soru7': np.random.randint(1, 6, n_samples),
    'soru8': np.random.randint(1, 6, n_samples),
    'soru9': np.random.randint(1, 6, n_samples),
    'soru10': np.random.randint(1, 6, n_samples),
}

# Hedef değişkenler için mantıksal kurallar
gezme_sevgisi = []
paraya_dikkat = []
maddi_durum = []

for i in range(n_samples):
    # Gezme sevgisi: soru1, soru3, soru7, soru9 ortalaması
    gezme_ort = np.mean([data['soru1'][i], data['soru3'][i], data['soru7'][i], data['soru9'][i]])
    if gezme_ort >= 4:
        gezme_sevgisi.append('Yüksek')
    elif gezme_ort >= 2.5:
        gezme_sevgisi.append('Orta')
    else:
        gezme_sevgisi.append('Düşük')
    
    # Paraya dikkat: soru2, soru4, soru6, soru8, soru10 ortalaması
    para_ort = np.mean([data['soru2'][i], data['soru4'][i], data['soru6'][i], data['soru8'][i], data['soru10'][i]])
    if para_ort >= 4:
        paraya_dikkat.append('Cimri')
    elif para_ort >= 2.5:
        paraya_dikkat.append('Orta')
    else:
        paraya_dikkat.append('Tutumlu')
    
    # Maddi durum: soru5 ve gezme/para ortalamalarına dayalı
    if data['soru5'][i] >= 4 and gezme_ort >= 3:
        maddi_durum.append('Zengin')
    elif data['soru5'][i] >= 2.5:
        maddi_durum.append('Orta')
    else:
        maddi_durum.append('Fakir')

data['gezme_sevgisi'] = gezme_sevgisi
data['paraya_dikkat'] = paraya_dikkat
data['maddi_durum'] = maddi_durum

# DataFrame oluşturma ve CSV'ye kaydetme
df = pd.DataFrame(data)
df.to_csv('sentetik_veri_500.csv', index=False)
print("500 satırlık veri seti 'sentetik_veri_500.csv' olarak kaydedildi.")

500 satırlık veri seti 'sentetik_veri_500.csv' olarak kaydedildi.


In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import numpy as np

# Sentetik veri setini yükleme (örnek olarak)
data = pd.read_csv("sentetik_veri_500.csv")

# Özellikler ve hedef değişkenler
X = data[['soru1', 'soru2', 'soru3', 'soru4', 'soru5', 'soru6', 'soru7', 'soru8', 'soru9', 'soru10']]
y_gezme = data['gezme_sevgisi']
y_para = data['paraya_dikkat']
y_maddi = data['maddi_durum']

# Kategorik hedefleri kodlama
le_gezme = LabelEncoder()
le_para = LabelEncoder()
le_maddi = LabelEncoder()

y_gezme_encoded = le_gezme.fit_transform(y_gezme)
y_para_encoded = le_para.fit_transform(y_para)
y_maddi_encoded = le_maddi.fit_transform(y_maddi)

# Veri setini bölme
X_train, X_test, y_gezme_train, y_gezme_test = train_test_split(X, y_gezme_encoded, test_size=0.2, random_state=42)
_, _, y_para_train, y_para_test = train_test_split(X, y_para_encoded, test_size=0.2, random_state=42)
_, _, y_maddi_train, y_maddi_test = train_test_split(X, y_maddi_encoded, test_size=0.2, random_state=42)

# Modelleri eğitme
rf_gezme = RandomForestClassifier(n_estimators=100, random_state=42)
rf_para = RandomForestClassifier(n_estimators=100, random_state=42)
rf_maddi = RandomForestClassifier(n_estimators=100, random_state=42)

rf_gezme.fit(X_train, y_gezme_train)
rf_para.fit(X_train, y_para_train)
rf_maddi.fit(X_train, y_maddi_train)

# Tahmin ve değerlendirme
y_gezme_pred = rf_gezme.predict(X_test)
y_para_pred = rf_para.predict(X_test)
y_maddi_pred = rf_maddi.predict(X_test)

print("Gezme Sevgisi - Doğruluk:", accuracy_score(y_gezme_test, y_gezme_pred))
print("Gezme Sevgisi - F1 Skoru:", f1_score(y_gezme_test, y_gezme_pred, average='weighted'))
print("Paraya Dikkat - Doğruluk:", accuracy_score(y_para_test, y_para_pred))
print("Paraya Dikkat - F1 Skoru:", f1_score(y_para_test, y_para_pred, average='weighted'))
print("Maddi Durum - Doğruluk:", accuracy_score(y_maddi_test, y_maddi_pred))
print("Maddi Durum - F1 Skoru:", f1_score(y_maddi_test, y_maddi_pred, average='weighted'))

# Önemli özellikler
print("Gezme Sevgisi - Önemli Özellikler:", rf_gezme.feature_importances_)
print("Paraya Dikkat - Önemli Özellikler:", rf_para.feature_importances_)
print("Maddi Durum - Önemli Özellikler:", rf_maddi.feature_importances_)

Gezme Sevgisi - Doğruluk: 0.87
Gezme Sevgisi - F1 Skoru: 0.8539744048684446
Paraya Dikkat - Doğruluk: 0.78
Paraya Dikkat - F1 Skoru: 0.7405510052122115
Maddi Durum - Doğruluk: 0.93
Maddi Durum - F1 Skoru: 0.929752380952381
Gezme Sevgisi - Önemli Özellikler: [0.15011888 0.05252316 0.16374004 0.05381158 0.05117444 0.0522803
 0.19995139 0.05238106 0.17236234 0.05165682]
Paraya Dikkat - Önemli Özellikler: [0.05584916 0.15686884 0.06205749 0.15117361 0.05961017 0.11164341
 0.06212881 0.1411589  0.06535446 0.13415516]
Maddi Durum - Önemli Özellikler: [0.0718232  0.0305779  0.05335575 0.03351854 0.62047741 0.02861817
 0.04434987 0.03250623 0.05839783 0.02637509]


In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
import numpy as np

# Veri setini yükleme
data = pd.read_csv("sentetik_veri_500.csv")

# Özellikler ve hedef değişkenler
X = data[['soru1', 'soru2', 'soru3', 'soru4', 'soru5', 'soru6', 'soru7', 'soru8', 'soru9', 'soru10']]
y_gezme = data['gezme_sevgisi']
y_para = data['paraya_dikkat']
y_maddi = data['maddi_durum']

# Kategorik hedefleri sayısal değerlere dönüştürme
le_gezme = LabelEncoder()
le_para = LabelEncoder()
le_maddi = LabelEncoder()

y_gezme_encoded = le_gezme.fit_transform(y_gezme)
y_para_encoded = le_para.fit_transform(y_para)
y_maddi_encoded = le_maddi.fit_transform(y_maddi)

# Veri setini eğitim ve test olarak bölme
X_train, X_test, y_gezme_train, y_gezme_test = train_test_split(X, y_gezme_encoded, test_size=0.2, random_state=42)
_, _, y_para_train, y_para_test = train_test_split(X, y_para_encoded, test_size=0.2, random_state=42)
_, _, y_maddi_train, y_maddi_test = train_test_split(X, y_maddi_encoded, test_size=0.2, random_state=42)

# Modelleri eğitme
rf_gezme = RandomForestClassifier(n_estimators=100, random_state=42)
rf_para = RandomForestClassifier(n_estimators=100, random_state=42)
rf_maddi = RandomForestClassifier(n_estimators=100, random_state=42)

rf_gezme.fit(X_train, y_gezme_train)
rf_para.fit(X_train, y_para_train)
rf_maddi.fit(X_train, y_maddi_train)

# Tahmin yapma
y_gezme_pred = rf_gezme.predict(X_test)
y_para_pred = rf_para.predict(X_test)
y_maddi_pred = rf_maddi.predict(X_test)

# Performans değerlendirme
print("Gezme Sevgisi Modeli:")
print("Doğruluk:", accuracy_score(y_gezme_test, y_gezme_pred))
print("F1 Skoru:", f1_score(y_gezme_test, y_gezme_pred, average='weighted'))
print("Karışıklık Matrisi:\n", confusion_matrix(y_gezme_test, y_gezme_pred))
print("\nParaya Dikkat Modeli:")
print("Doğruluk:", accuracy_score(y_para_test, y_para_pred))
print("F1 Skoru:", f1_score(y_para_test, y_para_pred, average='weighted'))
print("Karışıklık Matrisi:\n", confusion_matrix(y_para_test, y_para_pred))
print("\nMaddi Durum Modeli:")
print("Doğruluk:", accuracy_score(y_maddi_test, y_maddi_pred))
print("F1 Skoru:", f1_score(y_maddi_test, y_maddi_pred, average='weighted'))
print("Karışıklık Matrisi:\n", confusion_matrix(y_maddi_test, y_maddi_pred))

# Önemli özellikler
print("\nGezme Sevgisi - Önemli Özellikler:")
for feature, importance in zip(X.columns, rf_gezme.feature_importances_):
    print(f"{feature}: {importance:.4f}")
print("\nParaya Dikkat - Önemli Özellikler:")
for feature, importance in zip(X.columns, rf_para.feature_importances_):
    print(f"{feature}: {importance:.4f}")
print("\nMaddi Durum - Önemli Özellikler:")
for feature, importance in zip(X.columns, rf_maddi.feature_importances_):
    print(f"{feature}: {importance:.4f}")

# Örnek tahmin: Yeni bir anket cevabı için
yeni_veri = np.array([[4, 4, 4, 4, 4, 5, 3, 1, 3, 2]])  # İlk satırdan örnek
gezme_tahmin = le_gezme.inverse_transform(rf_gezme.predict(yeni_veri))[0]
para_tahmin = le_para.inverse_transform(rf_para.predict(yeni_veri))[0]
maddi_tahmin = le_maddi.inverse_transform(rf_maddi.predict(yeni_veri))[0]
print("\nÖrnek Tahmin:")
print(f"Yeni veri için gezme_sevgisi tahmini: {gezme_tahmin}")
print(f"Yeni veri için paraya_dikkat tahmini: {para_tahmin}")
print(f"Yeni veri için maddi_durum tahmini: {maddi_tahmin}")

Gezme Sevgisi Modeli:
Doğruluk: 0.87
F1 Skoru: 0.8539744048684446
Karışıklık Matrisi:
 [[15  7  0]
 [ 0 69  0]
 [ 0  6  3]]

Paraya Dikkat Modeli:
Doğruluk: 0.78
F1 Skoru: 0.7405510052122115
Karışıklık Matrisi:
 [[ 0  7  0]
 [ 1 68  2]
 [ 0 12 10]]

Maddi Durum Modeli:
Doğruluk: 0.93
F1 Skoru: 0.929752380952381
Karışıklık Matrisi:
 [[38  0  0]
 [ 0 34  3]
 [ 0  4 21]]

Gezme Sevgisi - Önemli Özellikler:
soru1: 0.1501
soru2: 0.0525
soru3: 0.1637
soru4: 0.0538
soru5: 0.0512
soru6: 0.0523
soru7: 0.2000
soru8: 0.0524
soru9: 0.1724
soru10: 0.0517

Paraya Dikkat - Önemli Özellikler:
soru1: 0.0558
soru2: 0.1569
soru3: 0.0621
soru4: 0.1512
soru5: 0.0596
soru6: 0.1116
soru7: 0.0621
soru8: 0.1412
soru9: 0.0654
soru10: 0.1342

Maddi Durum - Önemli Özellikler:
soru1: 0.0718
soru2: 0.0306
soru3: 0.0534
soru4: 0.0335
soru5: 0.6205
soru6: 0.0286
soru7: 0.0443
soru8: 0.0325
soru9: 0.0584
soru10: 0.0264

Örnek Tahmin:
Yeni veri için gezme_sevgisi tahmini: Orta
Yeni veri için paraya_dikkat tahmini: Orta

c:\Users\fatih\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\fatih\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\fatih\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [3]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

# Veri setini yükleme (modelleri eğitmek için, eğer henüz eğitilmediyse)
data = pd.read_csv("sentetik_veri_500.csv")

# Özellikler ve hedef değişkenler
X = data[['soru1', 'soru2', 'soru3', 'soru4', 'soru5', 'soru6', 'soru7', 'soru8', 'soru9', 'soru10']]
y_gezme = data['gezme_sevgisi']
y_para = data['paraya_dikkat']
y_maddi = data['maddi_durum']

# Kategorik hedefleri sayısal değerlere dönüştürme
le_gezme = LabelEncoder()
le_para = LabelEncoder()
le_maddi = LabelEncoder()

y_gezme_encoded = le_gezme.fit_transform(y_gezme)
y_para_encoded = le_para.fit_transform(y_para)
y_maddi_encoded = le_maddi.fit_transform(y_maddi)

# Veri setini eğitim ve test olarak bölme
X_train, X_test, y_gezme_train, y_gezme_test = train_test_split(X, y_gezme_encoded, test_size=0.2, random_state=42)
_, _, y_para_train, y_para_test = train_test_split(X, y_para_encoded, test_size=0.2, random_state=42)
_, _, y_maddi_train, y_maddi_test = train_test_split(X, y_maddi_encoded, test_size=0.2, random_state=42)

# Modelleri eğitme (eğer henüz eğitilmediyse)
rf_gezme = RandomForestClassifier(n_estimators=100, random_state=42)
rf_para = RandomForestClassifier(n_estimators=100, random_state=42)
rf_maddi = RandomForestClassifier(n_estimators=100, random_state=42)

rf_gezme.fit(X_train, y_gezme_train)
rf_para.fit(X_train, y_para_train)
rf_maddi.fit(X_train, y_maddi_train)

# Örnek bir kişi için anket cevapları
# Örneğin: Kullanıcıdan alınan yeni bir veri (10 soruya cevap, 1-5 arası)
yeni_kisi = np.array([[4, 4, 4, 4, 4, 5, 3, 1, 3, 2]])  # Örnek veri (ilk satırdan)

# Tahmin yapma
gezme_tahmin = le_gezme.inverse_transform(rf_gezme.predict(yeni_kisi))[0]
para_tahmin = le_para.inverse_transform(rf_para.predict(yeni_kisi))[0]
maddi_tahmin = le_maddi.inverse_transform(rf_maddi.predict(yeni_kisi))[0]

# Sonuçları yazdırma
print("Örnek Kişi için Tahminler:")
print(f"Gezme Sevgisi: {gezme_tahmin}")
print(f"Paraya Dikkat: {para_tahmin}")
print(f"Maddi Durum: {maddi_tahmin}")

Örnek Kişi için Tahminler:
Gezme Sevgisi: Orta
Paraya Dikkat: Orta
Maddi Durum: Zengin


c:\Users\fatih\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\fatih\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
c:\Users\fatih\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [4]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import joblib

# Veri setini yükleme
data = pd.read_csv("sentetik_veri_500.csv")

# Özellikler ve hedef değişkenler
X = data[['soru1', 'soru2', 'soru3', 'soru4', 'soru5', 'soru6', 'soru7', 'soru8', 'soru9', 'soru10']]
y_gezme = data['gezme_sevgisi']
y_para = data['paraya_dikkat']
y_maddi = data['maddi_durum']

# Kategorik hedefleri sayısal değerlere dönüştürme
le_gezme = LabelEncoder()
le_para = LabelEncoder()
le_maddi = LabelEncoder()

y_gezme_encoded = le_gezme.fit_transform(y_gezme)
y_para_encoded = le_para.fit_transform(y_para)
y_maddi_encoded = le_maddi.fit_transform(y_maddi)

# Veri setini eğitim ve test olarak bölme
X_train, X_test, y_gezme_train, y_gezme_test = train_test_split(X, y_gezme_encoded, test_size=0.2, random_state=42)
_, _, y_para_train, y_para_test = train_test_split(X, y_para_encoded, test_size=0.2, random_state=42)
_, _, y_maddi_train, y_maddi_test = train_test_split(X, y_maddi_encoded, test_size=0.2, random_state=42)

# Modelleri eğitme
rf_gezme = RandomForestClassifier(n_estimators=100, random_state=42)
rf_para = RandomForestClassifier(n_estimators=100, random_state=42)
rf_maddi = RandomForestClassifier(n_estimators=100, random_state=42)

rf_gezme.fit(X_train, y_gezme_train)
rf_para.fit(X_train, y_para_train)
rf_maddi.fit(X_train, y_maddi_train)

# Modelleri ve LabelEncoder nesnelerini kaydetme
joblib.dump(rf_gezme, 'rf_gezme_model.pkl')
joblib.dump(rf_para, 'rf_para_model.pkl')
joblib.dump(rf_maddi, 'rf_maddi_model.pkl')
joblib.dump(le_gezme, 'le_gezme.pkl')
joblib.dump(le_para, 'le_para.pkl')
joblib.dump(le_maddi, 'le_maddi.pkl')

print("Modeller ve LabelEncoder nesneleri kaydedildi.")

Modeller ve LabelEncoder nesneleri kaydedildi.
