deneme 2 1 bozuldu


In [36]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler , OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [37]:
df = pd.read_csv('cleanedManuel_data.csv')

In [38]:
df['location'] = df['location'].astype('category')
df['districk'] = df['districk'].astype('category')
df['neighborhood'] = df['neighborhood'].astype('category')
df['room'] = df['room'].astype('int')
df['living_room'] = df['living_room'].astype('int')
df['area'] = df['area'].astype('int')
df['age'] = df['age'].astype('int')
df['floor'] = df['floor'].astype('int')
df['price'] = df['price'].astype('int')

In [39]:
categorical_features = ['location', 'districk', 'neighborhood']
numerical_features = ['room', 'living_room', 'area', 'age', 'floor']

In [40]:
full_pipeline = ColumnTransformer([
    ('num', StandardScaler(), numerical_features),
    ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
])

In [41]:
X = df.drop('price', axis=1)
y = df['price']

In [42]:
bins = [0, 10000, 20000, 30000, 40000, 50000, 60000, 70000, 80000, 90000, 100000 ,110000]
labels = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ,11]    
y = pd.cut(y, bins=bins, labels=labels)
print(y.unique())

[5, 4, 2, 3, 7, ..., 9, 6, 10, 1, 11]
Length: 11
Categories (11, int64): [1 < 2 < 3 < 4 ... 8 < 9 < 10 < 11]


In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [44]:
model = Pipeline(steps=[
    ('preparation', full_pipeline),
    ('model', RandomForestClassifier(n_estimators=100))
])

In [45]:
model.fit(X_train, y_train)

Pipeline(steps=[('preparation',
                 ColumnTransformer(transformers=[('num', StandardScaler(),
                                                  ['room', 'living_room',
                                                   'area', 'age', 'floor']),
                                                 ('cat',
                                                  OneHotEncoder(handle_unknown='ignore'),
                                                  ['location', 'districk',
                                                   'neighborhood'])])),
                ('model', RandomForestClassifier())])

In [46]:
y_pred = model.predict(X_test)

In [47]:
print(confusion_matrix(y_test, y_pred))

[[  6  18   2   3   0   0   0   0   0   0   0]
 [  2 307 127   7   1   0   0   0   0   0   0]
 [  3 107 282  52   8   1   1   1   1   0   0]
 [  0  17  89  92  23   5   1   3   0   0   0]
 [  0   5  22  51  38  12   4   1   2   0   0]
 [  0   2   6  14  18  19   7   2   0   0   0]
 [  0   1   2   9   2   3  12   3   2   1   0]
 [  0   0   3   6   1   5   3   8   2   0   0]
 [  0   0   0   1   2   2   1   4   5   4   1]
 [  0   1   0   3   3   4   1   1   2   2   0]
 [  0   0   0   0   0   0   0   1   0   0   0]]


In [48]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print("Doğruluk (Accuracy):", accuracy)

Doğruluk (Accuracy): 0.5269993164730007


In [71]:
def tolerance_2(y_true, y_pred,tolerance):
    residuals = y_pred - y_true
    residuals[np.abs(residuals) <= tolerance] = 0
    ssr = np.sum(residuals ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1 - (ssr / sst)

def tolerance_percentage(y_true, y_pred,tolerance):
    residuals = y_pred - y_true
    residuals[np.abs(residuals) /y_true <= tolerance] = 0
    ssr = np.sum(residuals ** 2)
    sst = np.sum((y_true - np.mean(y_true)) ** 2)
    return 1 - (ssr / sst)

In [72]:
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred))


0.5527123580020482


In [32]:
print(type(y_test))
print(type(y_pred))
print(y_test.dtype)
print(y_pred.dtype)

<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>
category
int64


In [77]:
print(tolerance_2(y_test, y_pred, 1))
print(tolerance_percentage(y_test, y_pred, 0.7))

0.6709866115559472
0.9205520194343829


In [54]:
y_test = y_test.astype(int)
y_pred = y_pred.astype(int)